# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node CI

on: 
  push:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          HEAD_REF: ${{ toJson(github.ref) }}
          TITLE: $( echo ${{ github.ref }} | cut -d'/' -f 3)
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$HEAD_REF"
          echo "$TITLE"
