# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node CI

on: [push]

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow without inputs
#         uses: benc-uk/workflow-dispatch@v1
        continue-on-error: true
        id: dispatch
        run: echo FIRST
#         with:
#           workflow: My Workflow
#           token: ${{ secrets.PERSONAL_TOKEN }}
      - name: other action
        if: ${{ steps.dispatch.outcome != 'success' }}
        run: echo SECOND
