# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node CI

on: [push]

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        continue-on-error: true
        env:
          GITHUB_TOKENs: ${{ secrets.GITHUB_TOKEN }}
  second-request:
    name: SomeAction
    runs-on: ubuntu-latest
    steps:
      - name: other action
        if: ${{ !success() }}
        run: echo HERE
